events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl default_server;
        server_name _;

        ssl_certificate /etc/nginx/certs/ip.crt;
        ssl_certificate_key /etc/nginx/certs/ip.key;

        root /usr/share/nginx/html;
        index index.html;

        location ~* \.(css|js|mjs|html|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|json)$ {
            try_files $uri =404;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}